//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DersKayitAkademikTakip.Admin
{
    public partial class DerslerDuzenle
    {
        protected global::System.Web.UI.WebControls.Panel SuccessPanel;
        protected global::System.Web.UI.WebControls.Literal SuccessText;
        protected global::System.Web.UI.WebControls.Panel ErrorPanel;
        protected global::System.Web.UI.WebControls.Literal ErrorText;
        protected global::System.Web.UI.WebControls.TextBox txtDersKodu;
        protected global::System.Web.UI.WebControls.TextBox txtDersAdi;
        protected global::System.Web.UI.WebControls.TextBox txtKredi;
        protected global::System.Web.UI.WebControls.TextBox txtAktsKredi;
        protected global::System.Web.UI.WebControls.TextBox txtKontenjan;
        protected global::System.Web.UI.WebControls.TextBox txtDersDonemi;
        protected global::System.Web.UI.WebControls.DropDownList ddlHoca;
        protected global::System.Web.UI.WebControls.DropDownList ddlDersTipi;
        protected global::System.Web.UI.WebControls.Button btnIptal;
        protected global::System.Web.UI.WebControls.Button btnGuncelle;
    }
}
