//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DersKayitAkademikTakip.Admin
{
    public partial class KullanicilarDuzenle
    {
        protected global::System.Web.UI.WebControls.Panel SuccessPanel;
        protected global::System.Web.UI.WebControls.Literal SuccessText;
        protected global::System.Web.UI.WebControls.Panel ErrorPanel;
        protected global::System.Web.UI.WebControls.Literal ErrorText;
        protected global::System.Web.UI.WebControls.TextBox txtTC;
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        protected global::System.Web.UI.WebControls.TextBox txtAd;
        protected global::System.Web.UI.WebControls.TextBox txtSoyad;
        protected global::System.Web.UI.WebControls.DropDownList ddlRol;
        protected global::System.Web.UI.WebControls.TextBox txtSifre;
        protected global::System.Web.UI.WebControls.CheckBox chkAktif;
        protected global::System.Web.UI.WebControls.Button btnIptal;
        protected global::System.Web.UI.WebControls.Button btnGuncelle;
    }
}
