//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DersKayitAkademikTakip
{
    public partial class AkademikTakvimGoruntule
    {
        /// <summary>
        /// donemBaslik control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl donemBaslik;

        /// <summary>
        /// pnlTakvimYok control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlTakvimYok;

        /// <summary>
        /// pnlTakvim control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlTakvim;

        /// <summary>
        /// akademikYil control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl akademikYil;

        /// <summary>
        /// donemAdi control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl donemAdi;

        /// <summary>
        /// donemTarihi control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl donemTarihi;

        /// <summary>
        /// cardDersKayit control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl cardDersKayit;

        /// <summary>
        /// iconDersKayit control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl iconDersKayit;

        /// <summary>
        /// badgeDersKayit control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl badgeDersKayit;

        /// <summary>
        /// cardVize control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl cardVize;

        /// <summary>
        /// iconVize control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl iconVize;

        /// <summary>
        /// badgeVize control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl badgeVize;

        /// <summary>
        /// cardFinal control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl cardFinal;

        /// <summary>
        /// iconFinal control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl iconFinal;

        /// <summary>
        /// badgeFinal control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl badgeFinal;

        /// <summary>
        /// cardButunleme control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl cardButunleme;

        /// <summary>
        /// iconButunleme control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl iconButunleme;

        /// <summary>
        /// badgeButunleme control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl badgeButunleme;

        /// <summary>
        /// tdDonemBaslangic control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell tdDonemBaslangic;

        /// <summary>
        /// tdDonemBitis control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell tdDonemBitis;

        /// <summary>
        /// tdDersKayitBaslangic control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell tdDersKayitBaslangic;

        /// <summary>
        /// tdDersKayitBitis control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell tdDersKayitBitis;

        /// <summary>
        /// tdDersKayitDurum control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell tdDersKayitDurum;

        /// <summary>
        /// tdVizeBaslangic control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell tdVizeBaslangic;

        /// <summary>
        /// tdVizeBitis control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell tdVizeBitis;

        /// <summary>
        /// tdVizeDurum control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell tdVizeDurum;

        /// <summary>
        /// tdVizeNotGiris control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell tdVizeNotGiris;

        /// <summary>
        /// tdVizeNotGirisDurum control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell tdVizeNotGirisDurum;

        /// <summary>
        /// tdFinalBaslangic control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell tdFinalBaslangic;

        /// <summary>
        /// tdFinalBitis control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell tdFinalBitis;

        /// <summary>
        /// tdFinalDurum control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell tdFinalDurum;

        /// <summary>
        /// tdFinalNotGiris control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell tdFinalNotGiris;

        /// <summary>
        /// tdFinalNotGirisDurum control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell tdFinalNotGirisDurum;

        /// <summary>
        /// tdButunlemeBaslangic control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell tdButunlemeBaslangic;

        /// <summary>
        /// tdButunlemeBitis control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell tdButunlemeBitis;

        /// <summary>
        /// tdButunlemeDurum control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell tdButunlemeDurum;

        /// <summary>
        /// tdButunlemeNotGiris control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell tdButunlemeNotGiris;

        /// <summary>
        /// tdButunlemeNotGirisDurum control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell tdButunlemeNotGirisDurum;
    }
}
