//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DersKayitAkademikTakip.Ogrenci {
    public partial class DersKayit {
        protected global::System.Web.UI.WebControls.Panel SuccessPanel;
        protected global::System.Web.UI.WebControls.Literal SuccessText;
        protected global::System.Web.UI.WebControls.Panel ErrorPanel;
        protected global::System.Web.UI.WebControls.Literal ErrorText;
        protected global::System.Web.UI.WebControls.TextBox txtArama;
        protected global::System.Web.UI.WebControls.Button btnAra;
        protected global::System.Web.UI.WebControls.GridView gvDersler;
    }
}
