
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DersKayitAkademikTakip.Ogrenci {
    public partial class Derslerim {
        /// <summary>
        /// pnlUyari control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlUyari;

        /// <summary>
        /// lblUyari control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblUyari;

        /// <summary>
        /// pnlBasari control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlBasari;

        /// <summary>
        /// lblBasari control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblBasari;

        /// <summary>
        /// pnlHata control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlHata;

        /// <summary>
        /// lblHata control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblHata;

        /// <summary>
        /// gvKayitlar control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvKayitlar;
    }
}
