//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DersKayitAkademikTakip.Ogrenci {
    public partial class Notlarim {
        protected global::System.Web.UI.WebControls.GridView gvNotlar;
    }
}
