//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DersKayitAkademikTakip.Hoca {
    
    public partial class KayitOnay {
        
        protected global::System.Web.UI.WebControls.GridView gvKayitlar;
        
        protected global::System.Web.UI.WebControls.Panel SuccessPanel;
        
        protected global::System.Web.UI.WebControls.Label SuccessText;
        
        protected global::System.Web.UI.WebControls.Panel ErrorPanel;
        
        protected global::System.Web.UI.WebControls.Label ErrorText;
    }
}
